# Generated by Django 5.2 on 2025-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='slides/')),
                ('primary_button_text', models.CharField(blank=True, max_length=50)),
                ('primary_button_link', models.URLField(blank=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=50)),
                ('secondary_button_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
