# Generated by Django 5.0.1 on 2024-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_id_alter_category_id_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
