# Generated by Django 5.0.1 on 2024-01-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street',
        ),
    ]
